"""added breed column

Revision ID: 734f0f46209b
Revises: 
Create Date: 2019-12-26 22:02:53.561931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f0f46209b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
